# Generated by Django 6.0.2 on 2026-03-01 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('facility_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('fulfillment_center', 'Fulfillment Center'), ('sortation_center', 'Sortation Center'), ('delivery_station', 'Delivery Station'), ('cross_dock', 'Cross Dock'), ('other', 'Other')], default='warehouse', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facilities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tour_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('origin_facility', models.CharField(db_index=True, max_length=100)),
                ('origin_address', models.TextField(blank=True)),
                ('origin_city', models.CharField(blank=True, max_length=100)),
                ('origin_state', models.CharField(blank=True, max_length=50)),
                ('origin_zip', models.CharField(blank=True, max_length=20)),
                ('origin_datetime', models.DateTimeField(db_index=True)),
                ('origin_timezone', models.CharField(blank=True, max_length=10)),
                ('destination_facility', models.CharField(db_index=True, max_length=100)),
                ('destination_address', models.TextField(blank=True)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('destination_state', models.CharField(blank=True, max_length=50)),
                ('destination_zip', models.CharField(blank=True, max_length=20)),
                ('destination_datetime', models.DateTimeField()),
                ('destination_timezone', models.CharField(blank=True, max_length=10)),
                ('total_stops', models.PositiveIntegerField(default=2)),
                ('total_miles', models.DecimalField(decimal_places=1, max_digits=8)),
                ('deadhead_miles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_mile', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base_rate_per_mile', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('toll', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('driver_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], default='solo', max_length=10)),
                ('load_type', models.CharField(choices=[('drop', 'Drop'), ('live', 'Live'), ('hook', 'Hook')], default='drop', max_length=10)),
                ('equipment_type', models.CharField(default="53' Trailer", max_length=50)),
                ('equipment_provided', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=15)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20)),
                ('special_services', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.PositiveIntegerField()),
                ('leg_code', models.CharField(blank=True, max_length=50)),
                ('origin_facility', models.CharField(max_length=100)),
                ('destination_facility', models.CharField(max_length=100)),
                ('miles', models.DecimalField(decimal_places=1, max_digits=8)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('load_type', models.CharField(choices=[('drop', 'Drop'), ('live', 'Live'), ('hook', 'Hook')], default='drop', max_length=10)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('loaded', 'Loaded')], default='loaded', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='base.load')),
            ],
            options={
                'db_table': 'load_legs',
                'ordering': ['load', 'leg_number'],
                'unique_together': {('load', 'leg_number')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='base.RolePermission', to='base.permission'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('key', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='base.user')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='base.user')),
            ],
            options={
                'db_table': 'password_resets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='load',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loads', to='base.user'),
        ),
        migrations.AddField(
            model_name='load',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_loads', to='base.user'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='base.load')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='base.user')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='base.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='base.UserRole', through_fields=('user', 'role'), to='base.role'),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.PositiveIntegerField()),
                ('facility_code', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('equipment', models.CharField(blank=True, max_length=50)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_timezone', models.CharField(blank=True, max_length=10)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('departure_timezone', models.CharField(blank=True, max_length=10)),
                ('miles_to_next', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='base.loadleg')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='base.load')),
            ],
            options={
                'db_table': 'stops',
                'ordering': ['load', 'stop_number'],
                'unique_together': {('load', 'stop_number')},
            },
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['origin_facility', 'destination_facility'], name='loads_origin__c780cf_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status', 'created_at'], name='loads_status_9017bb_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['origin_datetime'], name='loads_origin__ed75fc_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['-payout'], name='loads_payout_1d3eff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
