# Generated by Django 6.0.2 on 2026-03-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, max_length=5, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['route_id'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('abbreviation', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'states',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.AddField(
            model_name='load',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='base.route'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['route', 'created_at'], name='loads_route_i_af4501_idx'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='base.state'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='base.state'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin_state', 'destination_state')},
        ),
    ]
